version: '3.8'

services:
  spring:
    build:
      context: ./spring
    volumes:
      - ./sqlite.db:/app/sqlite.db
    ports:
      - "6666:6666"

  flask:
    build:
      context: ./flask_app
    volumes:
      - ./sqlite.db:/app/sqlite.db
    ports:
      - "8086:8086"