version: '3.8'

services:
  spring:
    build:
      context: ./spring
    volumes:
      # - ./sqlite.db:/app/sqlite.db
      - ./volumes:/volumes
    ports:
      - "6942:6942"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:volumes/sqlite.db

  flask:
    build:
      context: ./flask
    volumes:
      - ./volumes:/volumes
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=sqlite:///volumes/sqlite.db